[Service]
ExecStart=
ExecStart=/usr/bin/docker compose --env-file /opt/stirling-pdf/.env -f /opt/stirling-pdf/compose.yml -f /opt/stirling-pdf/compose.ai.yml up -d --build
ExecStop=
ExecStop=/usr/bin/docker compose --env-file /opt/stirling-pdf/.env -f /opt/stirling-pdf/compose.yml -f /opt/stirling-pdf/compose.ai.yml down
